kind: Service
apiVersion: v1
metadata:
  name: tristian
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    hajimari.io/enable: "true"
    hajimari.io/icon: "tristian"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  type: ExternalName
  externalName: "ur.${SECRET_DOMAIN}"
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tristian-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    hajimari.io/enable: "true"
    hajimari.io/icon: "tristian"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`${SECRET_DOMAIN}`)
      kind: Rule
      priority: 1
      services:
        - name: tristian
          port: 3000
  tls:
    secretName: tristian-tls
