# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:auBQQngNBjFXzyLbzjaudXfyyiP45Cw=,iv:EqpWOhI4HmTIeUhikqi5Q8HrEu9ZUi3JfSCuhk0FKqU=,tag:hu9TVBqJTTavS4ZeSWnHgQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:s2yPj57T4Nww42jS1H2LGyJgcXJdxnkfvvFC/uoL/WCnLo5ExQ==,iv:FKeLSgCTYheC0i0/vTUgnHG0WQqzyGC9PcOHw5UqwF0=,tag:+JqOhnlh8gLBcqstLo1Bzg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:b/NgPxOHkQI+mUhwsBGBQA==,iv:jqwX4dwZS9Y/S8+5yOQtBkLYkptQFiD6jnw6qTYIJV4=,tag:Xhv2Lp807BTphaa6WfpEgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pzd40s3au5j5yt54j4cu2tw7lsp9755pmjs96jk5ny4m7v9ycc0svfy99k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZDQrTmYydEZyaEhZWHhR
            YmFMbU5lUFk1eDgxNWFzQmNWUnI4OE5GU3p3ClJkNWVPd3FBRTliV1pEZDRCVnFl
            NU9DYUltVW95bUJQelQvR25FbXUyTHcKLS0tIG5DeVF1TGxBaUZUY09uMVpLbkRk
            V1M4eUlNcnV5K0pka3ZwMjY1OGNKV2cKvC48abl667Hho3jUArtZibfZvOKUGSJO
            vyShlA64oD+dRydaEiDhdhKRWmZ/hVQaJydFqeLxNoiuCSw1Wk2e9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-22T02:02:32Z"
    mac: ENC[AES256_GCM,data:Dws2RhdYGSWrrwoYdgJ+H74X41FUr7ZjSQOe3cNLLL5hK8k0HUoqUTazIGiCJNXVFcJQjeF+F05EM4nKOTA4v9jxBz9jSo6oL3BRjIFkq2cYyxt+lGF9DnMcDH0MqsA/lL8wjjLn58zhMp05KF9zrTIjK6OQGSRw2/bpW23NwX4=,iv:ZhKCMjppzJ5SzcgAkxwyQbuSbUpc5rTo+ulOL14yek4=,tag:Ddenhau5jKsXZU2q34f12g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
