kind: Secret
ansible_user: ENC[AES256_GCM,data:e7Xpxp8W,iv:BRr2L0fhvDDKEdnyVFXdhTs0HlIwbJcOB8b7ejA42vA=,tag:9bVP9xsWD9Rq1GwxQFtnpQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:NtsO54F7plwAzg==,iv:fb5rzMfYTnQFNuz4fVNUrYD4WtKlksMwezXxsa06/aQ=,tag:J5Sz0WBnyciLW5OCW6Yw3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pzd40s3au5j5yt54j4cu2tw7lsp9755pmjs96jk5ny4m7v9ycc0svfy99k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoSEFpcGhLSnk2ZzNVb1JO
            RFpTVEp3VGs2WVNaQWpKTWtPNXZBL2RmbEhvCkNOdXF2RVlxbDgyMU9IeEtIOGxu
            VGpibkdxbE1QWitZNmRVeGNmYlpiQU0KLS0tIG1IWTROVXFCbTlMS2hrMG9YMFBw
            S3FoeDVvSlhFRS9oSHh2WUdIQmZ5YncKDKUYQzHl6BGkQDUOjfj1uudjdn5SMD6N
            IQqf4TVk/6ahe5M7tq5MNP8/K6Fb70Jv4YSpQ42LMEHj2ftKrlKHhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-22T02:02:33Z"
    mac: ENC[AES256_GCM,data:RC35CxtXNgfC2HPRReIw6AAAi9ObLLaFmwIqF2yQADYP9GqUBQ3Zz5N29jngVuCpzAxMa1Dt2UViHCYvb4sCv7Lo/8X4et1zL3wpZ/ynIwQ8JvbWjfLpv/MX3JRL1BwUpD+zi6jd8oJZdbhzmss0ZQ2y15Bd2YjKFR5lUfU066Y=,iv:B1bgg1gedyY9FsGQaPrA1ChXCNrRcBy+XFpxYB6xJaY=,tag:oW9zJB7F/ZzSjWJNHe/Cyw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.1
